# Generated by Django 2.2.1 on 2021-01-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_pay',
            field=models.CharField(choices=[('0', 'Расход'), ('1', 'Доход')], default='0', max_length=3),
        ),
    ]
