# Generated by Django 2.2.1 on 2021-01-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_type_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_pay',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Расход'), (1, 'Доход')], default=0, max_length=3),
        ),
    ]
