# Generated by Django 2.2.1 on 2021-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20210117_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Описание'),
        ),
    ]
